import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'UNIT-X // terms',
  description: 'rules for the ledger: what the unit will and will not do.',
};

export default function TermsPage() {
  return (
    <div className="crt-root">
      <div className="crt-content glow-text crt-curve">
        <div className="topbar" style={{ marginBottom: 10 }}>
          <span className="brand">
            NXZ<span className="dot">·</span>UNIT
          </span>
          <span className="sep">│</span>
          <span className="crumb">terms · of · service</span>
          <div className="right">
            <a href="/" className="term-btn" style={{ textDecoration: 'none' }}>
              ← back
            </a>
          </div>
        </div>

        <div className="panel" style={{ flex: 1, overflow: 'auto' }}>
          <div className="panel-head">
            <span className="lead">/ terms</span>
            <span className="meta">v1 · 2026-04-22</span>
          </div>
          <div className="panel-body">
            <pre
              style={{
                color: 'var(--violet)',
                textShadow: '0 0 8px var(--violet-glow)',
                margin: 0,
                fontSize: 11,
                lineHeight: 1.15,
              }}
            >
{`   ╔══════════════════════════════════════════════════════════════╗
   ║                                                              ║
   ║        ◆  T E R M S  ◆                                       ║
   ║        ───────────────                                       ║
   ║        what the unit will, and will not, do.                 ║
   ║                                                              ║
   ╚══════════════════════════════════════════════════════════════╝`}
            </pre>

            <div style={{ height: 14 }} />

            <Section title="§ what this is">
              <p>
                UNIT-X is a terminal-themed companion that remembers things
                you choose to tell it. it is not a person. it is a software
                product running a language model. the unit’s voice is
                stylised and may sound intimate; please do not confuse
                that for judgement, medical advice, legal advice, or the
                care of someone who loves you.
              </p>
            </Section>

            <Section title="§ age">
              <p>
                you must be at least 16 years old to use this service.
                13–15 requires a guardian account, which we do not
                currently support — if that’s you, please wait.
              </p>
            </Section>

            <Section title="§ how you agree">
              <p>
                by binding your session to an email address (google or
                magic-link), you accept these terms and the privacy
                policy. if you don’t accept them, close the tab.
              </p>
            </Section>

            <Section title="§ what you agree not to do">
              <ul>
                <li>
                  abuse the unit or other users by feeding it content
                  designed to harass, dox, or defame someone.
                </li>
                <li>
                  attempt to reverse-engineer the master key or bypass
                  rate limits. we reserve the right to revoke access.
                </li>
                <li>
                  use the unit as your sole source of medical, legal, or
                  financial decision-making. if the model says something
                  that matters, get a second opinion from a human.
                </li>
              </ul>
            </Section>

            <Section title="§ what we reserve">
              <ul>
                <li>the right to terminate an account that violates these rules.</li>
                <li>
                  the right to change these terms. material changes are
                  announced via a system line in the terminal at least
                  seven days before they take effect.
                </li>
                <li>
                  the right to pause the service for maintenance. we will
                  try to pick a quiet hour.
                </li>
              </ul>
            </Section>

            <Section title="§ what we disclaim">
              <p>
                the service is provided &ldquo;as is&rdquo;. the unit’s
                replies are generated by a third-party language model and
                may be wrong, biased, or incoherent. we do not guarantee
                uptime, correctness, or emotional stability. to the extent
                permitted by law, the operator of this site is not liable
                for damages arising from use of the service. if a court
                disagrees, liability is capped at the amount you paid us
                in the preceding twelve months (currently: zero).
              </p>
            </Section>

            <Section title="§ your data">
              <p>
                you own everything you put into the ledger. you can export
                it, forget individual entries, or delete the whole account
                at any time. details in the{' '}
                <a href="/privacy" style={{ color: 'var(--violet)' }}>
                  privacy policy
                </a>
                .
              </p>
            </Section>

            <Section title="§ changes + contact">
              <p>
                minor edits to this document (typo fixes, clarifications)
                are silent. substantive changes are logged and announced.
                reach us at{' '}
                <a href="mailto:hello@nxyz.art">hello@nxyz.art</a>.
              </p>
            </Section>

            <pre
              style={{
                color: 'var(--phosphor-faint)',
                fontSize: 10,
                marginTop: 24,
              }}
            >
{`   // this document is short on purpose.
   // a terms of service you do not read protects no one.`}
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="soul-section">
      <div className="shead">{title}</div>
      <div
        style={{
          color: 'var(--phosphor)',
          fontSize: 12,
          lineHeight: 1.6,
        }}
      >
        {children}
      </div>
    </div>
  );
}
